#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re


def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    dados = conexao.dados_residuais + dados
    conexao.dados_residuais = b''
    if dados == b'':
        return sair(conexao)
    
    if dados:
        requisicao, texto = dados.split(b' ', 1)
        #conexao.enviar(b':server PONG server :' + dados.split(b' ',1)[1])
        if requisicao == b'PING':
            conexao.enviar(b':server PONG server :' + texto)

        if requisicao == b'NICK':
            if validar_nome(texto):
                conexao.enviar(b':server 001 ' + texto + b' :Welcome\r\n')
                conexao.enviar(b':server 422 ' + texto + b' :MOTD File is missing\r\n')
            else:
                conexao.enviar(b':server 432 ' + texto + b' '+ texto + b' :Erroneous nickname\r\n')    

    print(conexao, dados)


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.dados_residuais = b''
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
