#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re


def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    dados = conexao.dados_residuais + dados
    conexao.dados_residuais = b''
    if dados == b'':
        return sair(conexao)

    # aqui está o passo 1
    if dados:
        for requisicao in dados:
            operacao , texto  = requisicao.split(b' ',1)
            if operacao.upper() == b'PING':                
                conexao.enviar(b':server PONG server :' + texto + b'\r\n')

    #aqui está o passo 2
    if not dados.endswith(b'\r\n'):
        dados = dados.split(b'\r\n')
        dados = list(filter((b'').__ne__, dados))
        conexao.dados_residuais += dados.pop(-1)
    
    else:
        dados = dados.split(b'\r\n')
        dados = list(filter((b'').__ne__, dados))

    print(conexao, dados)


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.dados_residuais = b''
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
